app/app/urls.py
#глобальная маршрутизация проекта
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #подключение файла urls из основого приложения
    path('', include('task_management.urls', namespace = 'task_management')) 
]

app/task_management/urls.py
# маршрутизация главной страницы
from django.urls import path
from task_management import views

app_name = "task_management"
urlpatterns = [
    path("", views.authorization, name="authorization"),
    path("registration/", views.registration, name="registration"),
    path("workertasks/", views.worker_tasks, name="worker_tasks"),
    path("workerstat/", views.worker_stat, name="worker_statistics"),
    path("workergantt/", views.worker_gantt, name="worker_gantt"),
    path("directorstat/", views.director_stat, name="director_statistics"),
    path("manageworkers/", views.workers_table, name = "manageworkers"),
    path("logout/", views.logout, name="logout")]

app/task_management/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    role = models.CharField(max_length=20, default="worker")
    
    class Meta:
        db_table = 'User'

    def __str__(self) -> str:
        return self.name
    
class Task(models.Model):
    name = models.CharField(max_length=255, unique=False)
    description = models.TextField()
    date_start = models.DateTimeField(null = True)
    date_end = models.DateTimeField(null = True)
    status = models.TextField()
    #внешний ключ Пользователь-Задачи
    user = models.ForeignKey(User, on_delete= models.CASCADE)

    class Meta:
        db_table = 'Task'

class Document(models.Model):
    name = models.CharField(max_length=255, unique=False)
    doc = models.FilePathField()

    #многие ко многим Задача-Документ
    tasks = models.ManyToManyField(Task)

    class Meta:
        db_table = 'Document'
        

app/task_management/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from task_management.models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
    username = forms.CharField()
    password = forms.CharField()

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

app/task_management/views.py
import json
from django.shortcuts import render
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from task_management.forms import UserLoginForm, RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from .models import Task, User

#проверка на роль пользователя для ограничения доступа работника к страницам руководителя
def check_user_condition(user):
    return user.role == "director"

# enter group
def authorization(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            if user.role == "worker":
                return HttpResponseRedirect(reverse("task_management:worker_tasks"))
            else:
                return HttpResponseRedirect(reverse("task_management:manageworkers"))
            if "next" in request.POST and request.POST["next"]:
                return HttpResponseRedirect(request.POST["next"])
        else:
            # Если форма не валидна, добавляем сообщение об ошибке
            for field, errors in form.errors.items():
                for error in errors:
                    messages.add_message(request, messages.ERROR, error)
            return render(
                request, "task_management/enter_templates/auth.html", {"form": form}
            )
    else:
        form = UserLoginForm()
        return render(
            request, "task_management/enter_templates/auth.html", {"form": form}
        )
def registration(request):
    print(request.method == "POST")
    
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            return redirect('task_management:manageworkers')
    else:
        form = RegistrationForm()
    return redirect('task_management:manageworkers')
def logout(request):
    auth.logout(request)
    return redirect(reverse('task_management:authorization'))

# worker group
@login_required
def worker_tasks(request):
    current_user = request.user.id  # Получение ID авторизованного пользователя
    # print(user_id)
    backlog_tasks = Task.objects.filter(status="backlog").filter(user_id=current_user)
    progress_tasks = Task.objects.filter(status="progress").filter(user_id=current_user)
    complete_tasks = Task.objects.filter(status="complete").filter(user_id=current_user)
    on_hold_tasks = Task.objects.filter(status="on_hold").filter(user_id=current_user)

    # Сериализация данных
    def format_datetime(dt):
        return dt.strftime("%Y-%m-%d %H:%M:%S") if dt else None

    # Сериализация данных
    tasks = {
        "backlog": json.dumps(
            [
                {
                    "id": task.id,
                    "name": task.name,
                    "description": task.description,
                    "date_start": format_datetime(task.date_start),
                    "date_end": format_datetime(task.date_end),
                    "status": task.status,
                }
                for task in backlog_tasks
            ]
        ),
        "progress": json.dumps(
            [
                {
                    "id": task.id,
                    "name": task.name,
                    "description": task.description,
                    "date_start": format_datetime(task.date_start),
                    "date_end": format_datetime(task.date_end),
                    "status": task.status,
                }
                for task in progress_tasks
            ]
        ),
        "complete": json.dumps(
            [
                {
                    "id": task.id,
                    "name": task.name,
                    "description": task.description,
                    "date_start": format_datetime(task.date_start),
                    "date_end": format_datetime(task.date_end),
                    "status": task.status,
                }
                for task in complete_tasks
            ]
        ),
        "onHold": json.dumps(
            [
                {
                    "id": task.id,
                    "name": task.name,
                    "description": task.description,
                    "date_start": format_datetime(task.date_start),
                    "date_end": format_datetime(task.date_end),
                    "status": task.status,
                }
                for task in on_hold_tasks
            ]
        ),
    }
    return render(
        request, "task_management/worker_templates/worker_kanban.html", {"tasks": tasks}
    )


@login_required
def worker_stat(request):
    return render(request, "task_management/worker_templates/worker_stat.html")


@login_required
def worker_gantt(request):
    return render(request, "task_management/worker_templates/worker_gantt.html")


# director group
@login_required
def director_stat(request):
    return render(request, "task_management/director_templates/director_stat.html")


@login_required
@user_passes_test(check_user_condition)
def workers_table(request):
    workers = User.objects.filter(role="worker")
    return render(request, "task_management/director_templates/director_workers_manage.html", {"workers": workers} )

app/main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'deps/icons/neongaer.png' %}" type="image/png">
    <title>Мавебап</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: url("{% static 'deps/images/auth-bg.jpg' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center; 
            background-size: cover; 
            {% comment %} height: 100%; {% endcomment %}
        }
        .login-container {
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            text-align: center;
            background-color: #3b54ca;
        }
        h2 {
            color: white;
            margin-top: -3px;
        }
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }
        button {
            padding: 10px 20px;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            background-color: #007bff; 
        }
        .button-container {
            display: flex;
            width: 100%;
        }
        .login-button {
            flex: 2; /* Button 1 takes 2/3 of the width */
            padding: 10px 20px;
            text-align: center;
            cursor: pointer;
            margin-right: 10px;
        }
        .register-button {
            flex: 1; /* Button 2 takes 1/3 of the width */
            padding: 10px 20px;
            text-align: center;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2 style="color: white;">Добро в Мавебап</h2>
        <input type="text" placeholder="Логин">
        <input type="password" placeholder="Пароль">
        <div class="button-container">
            <button class="login-button">Войти</button>
            <button href=" {%url "main:registration"%}" class="register-button">
                <a href="{% url 'main:registration' %}" style="text-decoration: none; color: inherit;">Зарегистрироваться</a>
            </button>
        </div>
        
    </div>
</body>
</html>

app/task_management/templates/task_management/director_templates/director_base.html
{% load static %}

<!DOCTYPE html> 
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Мавебап</title>
		<link rel="stylesheet" href="{% static "deps/styles/director_styles.css" %}">
		<link rel="stylesheet" href="{% static "deps/styles/kanban_styles.css" %}" />
		<link rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
			integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
			crossorigin="anonymous">
        <link rel="stylesheet" href= "{% static "deps/styles/gantt.css" %}">
		<link rel="stylesheet" href="{% static "deps/styles/director_styles.css" %}">
		<style>
			.logout-icon {
				cursor: pointer;
				width: 50px; 
				height: 50px; 
				background: url("{% static 'deps/icons/fordrug.png' %}") no-repeat center;
				background-size: contain;
				border: none; /* Убирает стандартную рамку кнопки */
        		padding: 0; /* Убирает стандартные отступы кнопки */
			}
		</style>
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">Мавебап</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="#">пуп
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">луп</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
						   role="button" data-toggle="dropdown" aria-haspopup="true"
						   aria-expanded="false">
							Dropdown
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>
					<li class="nav-item">
						<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#addWorkerModal">Добавить работника</button>
					</li>
				</ul>
			</div>
			<form action="{% url 'task_management:logout' %}" method="post">
				{% csrf_token %}
				<button type="submit" class="logout-icon" aria-label="Logout"></button>
			</form>
		</nav>

		{% comment %} модальное окно добавления работника {% endcomment %}
		
		{% block content %}
		
		{% endblock content %}

		<!-- Script -->
        <script src="{% static "deps/js/initialize-gantt.js" %}"></script>
		<script src="{% static "deps/js/gantt.js" %}"></script>
		<script src="{% static "deps/js/worker_manage.js" %}"></script>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
			integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
			crossorigin="anonymous"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
			integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
			crossorigin="anonymous"></script>
	</body>
</html>

app/task_management/templates/task_management/director_templates/director_stat.html
{% extends "task_management/director_templates/director_base.html" %}
{% load static %}

{% block content %}  
    <div id="chart"></div>
{% endblock content %}

app/task_management/templates/task_management/director_templates/director_workers_manage.html
{% extends "task_management/director_templates/director_base.html" %}
{% load static %}

{% block content %}  
<table>
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Изменить</th>
        </tr>
    </thead>
    <tbody>
        {% for worker in workers %}
        <tr>
            <td>{{ worker.first_name }}</td>
            <td>{{ worker.last_name }}</td>
            <td>
                <button class="chng-worker-btn" data-id="{{ worker.id }}">Изменить</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% comment %} модальное окно добавления работника {% endcomment %}
<div class="modal fade" id="addWorkerModal" tabindex="-1" role="dialog" aria-labelledby="addWorkerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addWorkerModalLabel">Добавить нового работника</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url "task_management:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Введите ваше имя" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Введите вашу фамилию" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введите пароль" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Подтвердите пароль" required>
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% comment %} модальное окно изменения данных работника {% endcomment %}
<div id="editModal" style="display:none;">
    <form>
        
    </form>
</div>
<div class="modal fade" id="changeWorkerModal" tabindex="-1" role="dialog" aria-labelledby="addWorkerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addWorkerModalLabel">Добавить нового работника</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url "task_management:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <label for="name">Имя:</label>
                        <input type="text" id="name" name="name">
                        <label for="surname">Фамилия:</label>
                        <input type="text" id="surname" name="surname">
                        <button type="submit">Сохранить изменения</button>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/task_management/templates/task_management/enter_templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'deps/icons/neongaer.png' %}" type="image/png">
    <title>Мавебап</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: url("{% static 'deps/images/auth-bg.jpg' %}"); 
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center; 
            background-size: cover; 
        }
        .login-container {
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            text-align: center;
            background-color: #3b54ca;
        }
        h2 {
            color: white;
            margin-top: -3px;
        }
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }
        button {
            padding: 10px 20px;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            background-color: #007bff; 
        }
        .button-container {
            display: flex;
            width: 100%;
        }
        .login-button {
            flex: 2; /* Button 1 takes 2/3 of the width */
            padding: 10px 20px;
            text-align: center;
            cursor: pointer;
            margin-right: 10px;
        }
        .register-button {
            flex: 1; /* Button 2 takes 1/3 of the width */
            padding: 10px 20px;
            text-align: center;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <form  action="{% url "task_management:authorization" %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value={{request.GET.next}}>
        {% endif %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Имя пользователя</label>
            <input type="text" class="form-control"
            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
            name="username" id="id_username"
            placeholder="Введите ваше имя пользователя"
            required>
        </div>
        <div class="mb-3">
            <label for="id_password" class="form-label">Пароль</label>
            <input type="password" class="form-control" name="password" id="id_password"
            placeholder="Введите ваш пароль" required>
        </div>
        <button type="submit" class="btn btn-dark btn-block">Войти</button>
        {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</body>
</html>

app/task_management/templates/task_management/enter_templates/reg.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'deps/icons/neongaer.png' %}" type="image/png">
    <title>Мавебап</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: url("{% static 'deps/images/auth-bg.jpg' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center; 
            background-size: cover; 
            {% comment %} height: 100%; {% endcomment %}
        }
        .register-container {
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            text-align: center;
            background-color: #3b54ca;
        }
        h2 {
            color: white;
            margin-top: -3px;
        }
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }
        button {
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="register-container">
        <h2 style="color: white;">Регистрация в Мавебап</h2>
        <input type="text" placeholder="Имя">
        <input type="text" placeholder="Фамилия">
        <input type="email" placeholder="Email">
        <input type="password" placeholder="Пароль">
        <button>Зарегистрироваться</button>
    </div>
</body>
</html>

app/task_management/templates/task_management/worker_templates/worker_base.html
{% load static %}

<!DOCTYPE html> 
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Мавебап</title>
		<link rel="stylesheet" href="{% static "deps/styles/kanban_styles.css" %}" />
		<link rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
			integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
			crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="{% url "task_management:worker_tasks" %}">Мавебап</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{% url "task_management:worker_statistics" %}">Статистика
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url "task_management:worker_gantt" %}">Диаграмма Ганта</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
							role="button" data-toggle="dropdown" aria-haspopup="true"
							aria-expanded="false">
							{{currentuser}}
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>
		
		{% block content %}
		
		{% endblock content %}

		<!-- Script -->
		<script>
			var backlogTasks = JSON.parse('{{ tasks.backlog|safe }}');
			var progressTasks = JSON.parse('{{ tasks.progress|safe }}');
			var completeTasks = JSON.parse('{{ tasks.complete|safe }}');
			var onHoldTasks = JSON.parse('{{ tasks.onHold|safe }}');
		</script>
		<script src= "{% static "deps/js/kanban_scripts.js" %}"></script>
		
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
			integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
			crossorigin="anonymous"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
			integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
			crossorigin="anonymous"></script>
	</body>
</html>

app/task_management/templates/task_management/worker_templates/worker_gantt.html
{% extends "task_management/worker_templates/worker_base.html" %}

{% block content %}
    
    <div>
        <p>
            гант
        </p>
    </div>

{% endblock content %}
    

app/task_management/templates/task_management/worker_templates/worker_stat.html
{% extends "task_management/worker_templates/worker_base.html" %}

{% block content %}
<div>
    <p>
        Статистика
    </p>
</div>
{% endblock content %}